### ISSUE TITLE
[00:50:00] ERROR    Internal stop codon detected in sequence sp1102chr03.35183.t1                                                    utility.py:32

### ISSUE THREAD

**Issue by panxinfeng661** [SwiftSeal/resistify#29]
This is that protein sequence
```
>sp1102chr03.35183.t1
KRHSCLDVARTGDGGAEDGRDRHAVGAWRLGRRGTCYVVGRKEKRHSCLDVARTGDGGAEDGRDRHAVGAWRLGRRGTCYVVGRKEKRHSCLDVARTGDG
GAEDGRDRHAVGAWRLGRRGTCYVVGRKEKRHSCLDVARTGDGGAEDGRDRHAVGAWRLGRRGTCYVVGRKEKRHSCLDVARTGDGGAEDGRDRHAVGAW
RLGRRGTCYVVGRKEKRHSCLDVARTGDGGAEDGRDRHAVGAWRLGRRGTCYVVGRKEKRHSCLDVARTGDGGAEDGRDRHAVGA*RLGRRGTCYVVGRK
EKRHSCLDVARTGDGGAEDGRDRHAVGAWRLGRRGTCYVVGRKEKRHSCLDVARTGDGGAEDGRDRHAVGAWRLGRRGTCYVLGRKEKRHSCLDVARTGD
GGAEDGRDRHAVGAWRLGRRETWYAVGRKEKRHSCVDVATTGDRGAEDRRDRGAEDGRGRLAVGAWRLGRRGTCYVLGRKEKRHSCLDVARTGDGGAEDG
RDRHAVGEWRLGRRGTCYVVGRKEKRHSCLDVARTGDGGAEDGRNRHAVGA

```
which is  Internal stop codon,and how to address this issue?

**Comment by SwiftSeal** [comment]
Hi @panxinfeng661 

`Resistify` is indicating that there is a `*` character in the sequence, which HMMER cannot handle so are rejected. I can see an asterisk in the sequence you have provided. To remove sequences with internal stop codons, you could use [`seqkit`](https://bioinf.shenwei.me/seqkit/):

`seqkit grep --by-seq --invert-match -r --pattern '\*[^$]' <your_sequences.fa>`

**Comment by SwiftSeal** [comment]
A quick note - the latest version will now report and *skip* sequences like this, rather than exiting with an error. Should make it slightly easier to work with :)
