### ISSUE TITLE
the program seems stucked

### ISSUE THREAD

**Issue by yilunhuangyue** [SwiftSeal/resistify#33]
Thank you very much for develping the program. It is very useful for my project. However, I met an problem when running it.
The command i used was: resistify nlr round4.all.prot.fa
Then I got the log file like this:
[15:21:08] INFO     Welcome to Resistify version 0.6.2!                         
           WARNING  Sequence                                                    
                    augustus_masked-Chr_02_nlr_25-processed-gene-0.0-mRNA-1 is  
                    less than 28 codons - skipping this sequence...             
           WARNING  Sequence                                                    
                    augustus_masked-Chr_08_nlr_26-processed-gene-0.2-mRNA-1 is  
                    less than 28 codons - skipping this sequence...             
           WARNING  Sequence                                                    
                    augustus_masked-ptg000046l_nlr_3-processed-gene-0.3-mRNA-1  
                    is less than 28 codons - skipping this sequence...          
           INFO     Searching for NLRs...                                       
           INFO     Running hmmsearch...                                        
[15:21:10] INFO     321 NLRs identified...                                      
[15:21:11] INFO     Running NLRexpress - this could take a while...             
[15:23:53] ERROR    * is not a float.                                           
                    augustus_masked-Chr_08_nlr_10-processed-gene-0.5-mRNA-1     
                    /tmp/tmplz84cb2z/seq.fa.out-1.hmm                           
[15:24:04] ERROR    * is not a float.                                           
                    snap_masked-Chr_08_nlr_29-processed-gene-0.0-mRNA-1         
                    /tmp/tmpc3ooh1md/seq.fa.out-1.hmm                           

The program is running for more than one day and I can see multiple thread named "pt_main_thread" in the  backend of server as "Sleeping" status.  I am not sure what is the problem. Thank you very much for any help.

**Comment by SwiftSeal** [comment]
Hi @yilunhuangyue

That seems like a bug to me - could you post the sequences of augustus_masked-Chr_08_nlr_10-processed-gene-0.5-mRNA-1 and snap_masked-Chr_08_nlr_29-processed-gene-0.0-mRNA-1? They might have some characters which are causing issues - I'll test them on my end

**Comment by yilunhuangyue** [comment]
Thanks for your quick reply. I have solved the issue. I used gffread to extract protein sequences and the  stop coden was indicated by the charactor '.'. I remove the charactor and the program was successfully finished.

**Comment by SwiftSeal** [comment]
Ahh I didn't think of that! I have released v0.6.3 to fix this. Thanks for letting me know :)
