### ISSUE TITLE
runtime estimate for the prr subtool ?

### ISSUE THREAD

**Issue by colindaven** [SwiftSeal/resistify#34]
Hi Moray,

just trying the `prr` tool.  I wonder if you have rough runtime estimates for 30k proteins ? I believe it is a lot slower than the `nlr` tool which seemed to be done in a few hours on the same data. 

`prr `seemed to take 13m for just 5 (not 5k!) proteins, and has not completed overnight for the 30k. Also, I'm not sure where the logs are being written (maybe in the TRANSFORMERS_CACHE dir ? ), but can't find them. Maybe Nextflow is doing something nefarious with them ?

Is this duration what you'd expect ?

Thanks
Colin

**Comment by SwiftSeal** [comment]
Hi @colindaven 

Does the PRR job have access to a GPU? If it does, running it with --debug enabled will make it print the device it is using. Sometimes, despite having access to a GPU it runs in CPU mode only!

If it is running only on CPU, it is unfortunately very slow!

**Comment by SwiftSeal** [comment]
The (resistify) logs should just be going to stdout also

**Comment by SwiftSeal** [comment]
Okay I've been testing this on google colab and I noticed that even with access to a cuda device, conda wasn't installing a gpu version of pytorch. As a workaround, `conda install pytorch-gpu bioconda::resistify` seems to force it to install the correct version, and `torch.cuda.is_available()` runs correctly! I think it is important to specify pytorch-gpu first, otherwise conda sometimes resolves a cpu only version.

**Comment by colindaven** [comment]
Ah I see, that makes sense. I'll have a go at rebuilding the container and trying to verify the gpu is going to be used tomorrow. 

I have the added fun of a job scheduler too so this will take some time to get right.

After reading the tmbed paper, it seems a couple of hours should be about right with a gpu and a 30k dataset.

**Comment by colindaven** [comment]
I've respecified the container using pytorch-gpu but I think it is running PRR on cpu again. It's unclear, but seems v slow for 5 test proteins.

```
RUN micromamba activate && \
    micromamba install -y -c conda-forge -c bioconda pytorch-gpu resistify 


#Maybe I need to run two installs, eg
RUN micromamba activate && \
    micromamba install -y -c conda-forge -c bioconda pytorch-gpu

RUN micromamba activate && \
    micromamba install -y -c conda-forge -c bioconda resistify 
```

For debugging, maybe you could add the result of 

`torch.cuda.is_available()
`
to the stdout logs ? Eg 

`INFO - gpu detected by torch.cuda.is_available()`

```
[10:31:42] INFO     Welcome to Resistify version 0.6.3!                         
           INFO     Searching for PRRs...                                       
           INFO     Running hmmsearch...                                        
           INFO     Predicting transmembrane domains... 

```
Perhaps it would also be possible to display progress - eg 

`INFO Finished 100 protein PRR predictions
`

Just a few thoughts really.

**Comment by SwiftSeal** [comment]
If you run `resistify --debug prr ...` It will print which device it's using! I think a progress bar is a good idea, will probably add one to the nlrexpress runner also, like:
![image](https://github.com/user-attachments/assets/7aa26e1f-7a0e-416b-8d8b-b287ad5522c7)

**Comment by SwiftSeal** [comment]
In next version I've also made it print a warning if device is cpu, rather than hiding it in the logs :-)

**Comment by SwiftSeal** [comment]
Okay progress bars and warnings added - I've also increased the threshold of several of the RLP/RLK HMM profiles as some (WAKS in particular) where being erroneously reported. I'll push this update once I can test it on our HPC, want to make sure I haven't broken something else... If you want to try it in the meantime, main branch should be stable

**Comment by colindaven** [comment]
Thanks for the new release. With the new version, but probably more importantly new Dockerfile, I can now run 10000 lines of protein in 13m on a GPU, vs the same file not completing overnight on CPU.

The Dockerfile using micromamba looks like this - you were right, pytorch-gpu from bioconda was causing issues. I tried multiple other routes without success but this one works great.

```
RUN micromamba activate && \
    micromamba install -y -c conda-forge pytorch-gpu bioconda::resistify
```

Thanks again
