### ISSUE TITLE
MADA and CJID always false

### ISSUE THREAD

**Issue by colindaven** [SwiftSeal/resistify#5]
Hello,

thanks for the nice tool. I've run a couple of protein sets and got decent results. However MADA and CJID are always false in entire proteomes. What is the criteria for these, and shouldn't they be true at least sometimes ? I work on plants.

In other words for the MADA motifs, how conserved does this motif need to be  to be registered ?

`consensus MADAxVSFxVxKLxxLLxxEx (MADA motif)`

Thanks

```
Sequence        Length  Domains Classification  NBARC_motifs    MADA    CJID
gene000035.1                                         1485    CNL     CNL     9       False   False

```

To part answer my own question, it seems only MADA is necessary and it must be right at the start of the sequence to be picked up, correct?

```
# MADA motif must be at the start of the sequence to be valid
--
58 | if domain == "MADA" and start != 1:
59 | continue
```

And it seems I have only a few `MAD` + W,I,S, not `MADA `motifs, and none are at the start of the protein.

**Comment by SwiftSeal** [comment]
Hi @colindaven !

That's interesting 🤔 what species are you working with if you don't mind me asking? The MADA motif was taken from https://doi.org/10.7554/eLife.49956 - I made the decision to anchor it to the N-terminal as it's expected to be on the N-terminal. That being said perhaps there are cases where it is not? I'll look into it... Either way it should be expected to be present in a % of CNLs. The current evalue threshold might be too strict for more distant plant species, I'll add an option to manually set this threshold in the next version if that would be helpful?

The CJID domain is biased towards TNLs from dicotyledonous plant species which may impact observation frequency. Again, probably an argument to be made for relaxing evalues. Development of Resistify was mostly done with the RefPlantNLR DB and Solanum genomes, so I might need to provide alternative options for distant species.

Thanks!

**Comment by SwiftSeal** [comment]
No problem! My own research does not focus much on MADA domains either so it could do with some extra development.
Yes, the "MADALs" are more frequent in barley etc (and are more frequently not at the first position of the sequence).
I've got some folk at my institute who work on barley and I believe have been testing Resistify - so I think adjusting to account for this is a good idea.
Your suggestion of a second column is good as I think keeping a separation betweening high-confidence and low-confidence hits will be useful.
There are some `hmmsearch` arguments I've been intending to expose to the user as well.
I'll be away at a conference next week but I'll do some testing when I get back! I'll open a dev branch for this :)

**Comment by SwiftSeal** [comment]
I've released a new version which now reports MADA and MADAL motifs in line with their source publications parameters. I've left C-JID untouched for now, might focus on this later. A release should be available on PyPI, conda (and docker!) soon, but the source is available for testing on GitHub now :)
